def sectionhead(n,title,body=''):
 return '<div class="section-head reveal"><span class="section-index" aria-hidden="true">'+n+'</span><h2>'+fmt(title)+'</h2>'+(''.join(para(x) for x in body) if body else '')+'</div>'
def closing(title,body='',secondary=True):
 return '<div class="section-close reveal"><h3>'+fmt(title)+'</h3>'+(para(body) if body else '')+action(secondary)+'</div>'

# Final client revision; the newer chat instruction replaces the proposed video.
hero='<section class="hero" id="inicio"><div class="hero-photo">'+img('casal-editado.webp','Casal conversando em casa em um momento de tranquilidade.',priority=True)+'</div><div class="hero-inner"><div class="hero-copy"><h1>A <mark>cannabis medicinal</mark> pode ser a solução terapêutica para o seu <strong>bem-estar.</strong></h1>'+para(S[0][4],'hero-subtitle')+para('Se você convive com condições que já fazem parte da sua rotina, vale entender como esse tratamento funciona e conversar com um médico que avalie o seu caso.','hero-support')+'<div class="actions"><a class="cta" href="#condicoes"><span>ENTENDA COMO A CANNABIS MEDICINAL PODE AJUDAR</span><span class="cta-arrow" aria-hidden="true">↓</span></a><a class="secondary" href="'+MD+'" target="_blank" rel="noopener noreferrer">Já sabe o próximo passo? Escolher um médico prescritor →</a></div></div></div></section>'
condition_names=['Alzheimer','Ansiedade','Autismo','Depressão','Dor crônica','Dor orofacial','Epilepsia','Espasticidade','Insônia','Náuseas e vômitos']
strip_text=' · '.join(condition_names)
strip='<div class="condition-strip" aria-label="Condições clínicas"><div class="ticker"><div>'+strip_text+'</div><div aria-hidden="true">'+strip_text+'</div></div><div class="strip-controls"><button type="button" data-strip="-1" aria-label="Condições anteriores">←</button><button type="button" data-strip="1" aria-label="Próximas condições">→</button></div></div>'
s=S[1]
rest='<section class="recognition section" id="rotina"><div class="wrap">'+sectionhead('01',s[1])+'<div class="routine-grid" id="rotina-cards" tabindex="0" aria-label="Quatro cenas da rotina; deslize para ver mais">'
for i,photo,alt in [(2,'cansaco.webp','Pessoa descansando na cama.'),(0,'caminhada.webp','Casal de idosos caminhando juntos.'),(4,'ansiedade.webp','Mulher pensativa junto à janela.'),(5,'familia.webp','Família reunida na sala.')]:
 rest+='<article class="routine-card reveal">'+img(photo,alt)+'<div><h3>'+fmt(s[2+i*2])+'</h3>'+para(s[3+i*2])+'</div></article>'
rest+='</div><div class="swipe-progress" aria-hidden="true"><span></span></div>'+closing(s[17],s[19],False)+'</div></section>'

science_pars=['Nosso organismo possui um sistema chamado sistema endocanabinoide, envolvido na regulação de diferentes processos, como sono, dor, humor, apetite e resposta ao estresse. Os canabinoides da Cannabis, como CBD e THC, podem interagir de diferentes formas com essa rede de sinalização — e é essa relação que vem sendo estudada em diferentes contextos terapêuticos.','Isso mesmo: o seu corpo já produz os próprios canabinoides. Eles se conectam a receptores espalhados pelo organismo e ajudam a manter o equilíbrio de vários processos do dia a dia.']
rest+='<section class="science section" id="ciencia"><div class="wrap">'+sectionhead('02','O que o sistema endocanabinoide ==tem a ver com isso==?')+'<div class="science-revised"><div class="science-card reveal">'+para(science_pars[0])+para(science_pars[1],'emphasis')+'</div><figure class="science-illustration reveal"><a href="assets/sistema-endocanabinoide.png" target="_blank" rel="noopener" aria-label="Ampliar ilustração do sistema endocanabinoide">'+img('sistema-endocanabinoide.png','Sistema endocanabinoide: CB1 mais presente no sistema nervoso; CB2 mais presente em tecidos periféricos e sistema imune. Participa da regulação de sono, dor, humor e resposta ao estresse.')+'</a><figcaption>Representação ilustrativa · Toque na imagem para ampliar.</figcaption><div class="receptor-legend"><p><strong>CB1</strong> Mais presente no sistema nervoso.</p><p><strong>CB2</strong> Mais presente em tecidos periféricos e sistema imune.</p></div></figure></div>'
med=['No uso medicinal, existe uma intenção terapêutica planejada por um profissional habilitado. A formulação é conhecida, a concentração é definida e a dose é individualizada de acordo com a condição, a resposta do paciente e os objetivos do tratamento.','Dependendo da formulação, o produto pode conter CBD, THC e outros componentes da planta, em diferentes concentrações e proporções.','No Brasil, existem diferentes formas regulamentadas de acesso a produtos à base de cannabis mediante prescrição, incluindo produtos disponíveis em farmácias e vias específicas de importação.']
rest+='<div class="medicinal-panel reveal"><div class="medicinal-image">'+img('frasco-editado.webp','Mãos segurando conta-gotas e frasco âmbar sem rótulo.')+'</div><div class="medicinal-copy"><h3>Cannabis medicinal <mark>não é</mark> uso recreativo.</h3>'+para(med[0])+para(med[1])+'<div class="care-principles"><span>Objetivo terapêutico</span><span>Formulação definida</span><span>Dose individualizada</span><span>Avaliação profissional</span></div>'+para(med[2],'info-box')+'</div></div><div class="science-close reveal">'+action(False)+'</div></div></section>'

# Ten distinct conditions, matching the final client list. Descriptions do not assert efficacy.
condition_info=[('Sintomas associados à memória e ao comportamento.','cuidado.webp'),('A ansiedade que continua presente na rotina.','ansiedade-nova.png'),('Cuidado individualizado para pessoas no espectro autista.','familia.webp'),('Atenção à saúde mental e ao bem-estar.','ansiedade.webp'),('A dor que persiste e interfere no dia a dia.','caminhada.webp'),('Dor na região da face e da boca.','tensao.webp'),('Avaliação das particularidades de cada caso.','epilepsia-referencia.png'),('Rigidez e contrações musculares ligadas a condições neurológicas.','espasticidade-referencia.png'),('Dificuldades para iniciar ou manter o sono.','insonia.webp'),('Sintomas que precisam de avaliação individual.','consulta-ilustrativa.png')]
conditions=[{'title':name,'intro':info[0],'body':info[0]+' A indicação, a formulação e o acompanhamento devem ser avaliados por um profissional habilitado, considerando a sua história e os objetivos do cuidado. Converse com a equipe para entender o próximo passo.','image':info[1]} for name,info in zip(condition_names,condition_info)]
def condcard(i):
 c=conditions[i]
 return '<button class="condition-card" data-condition="'+str(i)+'" aria-haspopup="dialog">'+img(c['image'],'Cena ilustrativa de cuidado e rotina.')+'<span class="condition-content"><span class="condition-title">'+fmt(c['title'])+'</span><span class="condition-intro">'+fmt(c['intro'])+'</span><span class="condition-plus" aria-hidden="true">+</span></span></button>'
s=S[3]
rest+='<section class="conditions section" id="condicoes"><div class="wrap">'+sectionhead('03','Conheça as condições clínicas da ==Canabinote==.',['Explore as dez condições que fazem parte da curadoria da Canabinote. A avaliação e a indicação de tratamento são individuais.','Toque em uma condição para saber mais.'])+'<div class="condition-carousel reveal"><div class="condition-track" id="condicoes-cards" tabindex="0" aria-label="Carrossel das dez condições clínicas">'+''.join(condcard(i) for i in range(10))+'</div><div class="carousel-controls"><button data-carousel="-1" aria-label="Condição anterior">←</button><button class="autoplay-toggle" aria-label="Pausar movimento das condições">Pausar</button><button data-carousel="1" aria-label="Próxima condição">→</button></div></div><div class="section-close reveal"><h3 class="small-close">Não encontrou a sua condição aqui? Fale com a gente e tire a sua dúvida.</h3>'+action()+'</div></div></section>'

s=S[4]
rest+='<section class="journey section" id="jornada"><div class="wrap">'+sectionhead('04',s[1],['São 4 passos para sair da dúvida e chegar a um cuidado médico guiado por ciência, com praticidade e segurança.'])+'<div class="timeline"><div class="timeline-rail" aria-hidden="true"><span></span></div>'
profile='<div class="illustrative-profile">'+img('medica-ilustrativa.png','Retrato ilustrativo de uma médica.')+'<div><strong>Encontre seu médico</strong><span>Formação e especialidade</span><span class="profile-tag">Conheça o perfil</span></div></div><small class="illustration-note">Imagem ilustrativa</small>'
appointment='<div class="appointment-phone"><div class="phone-notch"></div><div class="phone-header">Canabinote <span>✓</span></div><div class="appointment-message"><span class="calendar-icon" aria-hidden="true">▦</span><strong>Sua consulta está confirmada!</strong><span>Data e horário escolhidos</span><span>Informações da consulta no WhatsApp</span><i aria-hidden="true">✓✓</i></div></div><small class="illustration-note">Representação ilustrativa</small>'
monitor='<div class="monitor-scene">'+img('paciente-acompanhamento.png','Mulher acompanhando seu cuidado pelo celular, em cena ilustrativa.')+'<div class="wellbeing-card"><strong>Como você está hoje?</strong><span>☺ Muito bem</span><span>☺ Bem</span><span>◉ Regular</span><span>◉ Mal</span><span>◉ Muito mal</span></div></div>'
steps=[(4,[5],'perfil',profile),(6,[7],'agendamento',appointment),(8,[9,10],'consulta',img('consulta-ilustrativa.png','Cena ilustrativa de uma médica conversando com uma paciente.')),(11,[12],'acompanhamento',monitor)]
for i,(title,pars,kind,visual) in enumerate(steps):
 rest+='<article class="journey-step reveal"><div class="step-visual '+kind+'">'+visual+'</div><span class="step-number" aria-hidden="true">0'+str(i+1)+'</span><div class="step-copy"><h3>'+fmt(s[title])+'</h3>'+''.join(para(s[j]) for j in pars)+'</div></article>'
rest+='</div>'+closing(s[14])+'</div></section>'

why_copy='Com cannabis medicinal, a consulta é apenas o começo. A Canabinote ajuda a transformar esse cuidado em uma jornada mais organizada, com orientações claras, registro da evolução e acompanhamento ao longo do tempo.'
rest+='<section class="why section" id="canabinote"><div class="wrap">'+sectionhead('05','Por que começar pela ==Canabinote==?',[why_copy])+'<figure class="comparison care-comparison reveal"><div class="compare-stage" style="--split:50%"><div class="compare-scene scene-after" role="img" aria-label="Cena ilustrativa com acompanhamento: mulher consulta seu celular com orientações organizadas."><svg viewBox="887 0 887 887" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><image href="assets/comparacao-acompanhamento.png" width="1774" height="887"/></svg></div><div class="care-notifications"><span><b>▦ Lembrete de medicação</b>Conforme a orientação médica</span><span><b>Mensagem do seu médico</b>Como você está se sentindo?</span><span><b>↗ Evolução do tratamento</b>Seus registros em um só lugar</span></div><div class="compare-before"><div class="compare-scene scene-before" role="img" aria-label="Cena ilustrativa sem acompanhamento: mulher com dúvidas entre papéis e mensagens."><svg viewBox="0 0 887 887" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><image href="assets/comparacao-acompanhamento.png" width="1774" height="887"/></svg></div></div><div class="compare-label left">Sem acompanhamento</div><div class="compare-label right">Com acompanhamento</div><div class="compare-handle" aria-hidden="true"><span>↔</span></div><input type="range" min="5" max="95" value="50" aria-label="Compare a organização do cuidado sem e com acompanhamento"></div><figcaption>Arraste para comparar · Cenas e telas ilustrativas da organização do cuidado.</figcaption></figure><div class="brand-statement reveal"><p>A diferença não está apenas na prescrição,</p><p>mas na forma como o cuidado continua</p><p>ao longo da jornada.</p></div><div class="center-actions">'+action()+'</div></div></section>'

s=S[6]
rest+='<section class="final-section" id="conversar"><div class="final-photo">'+img('casal-editado.webp','Casal aproveitando um momento de tranquilidade em casa.')+'</div><div class="wrap final-inner"><div class="final-copy reveal"><h2>'+fmt(s[1])+'</h2>'+para('A cannabis medicinal pode ser uma possibilidade para diferentes condições de saúde, mas sua indicação deve ser avaliada de forma individual, com orientação médica, informação de qualidade e acompanhamento ao longo da jornada.')+action(False)+'<a class="secondary final-team" href="'+html.escape(WA)+'" target="_blank" rel="noopener noreferrer">Falar com a nossa equipe →</a></div></div></section><footer><div class="wrap footer-inner">'+logo()+para(s[10])+'</div></footer>'
rest+='<dialog id="condition-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Fechar detalhes">×</button><div class="dialog-image"></div><div class="dialog-body"><h2 id="dialog-title"></h2><p id="dialog-description"></p>'+action(False)+'</div></dialog><a class="floating-wa" href="'+html.escape(WA)+'" target="_blank" rel="noopener noreferrer" hidden>Quero saber mais <span aria-hidden="true">↗</span></a><script type="application/json" id="condition-data">'+json.dumps(conditions,ensure_ascii=False).replace('</','<\/')+'</script>'


