def sectionhead(n,title,body=''):
 return '<div class="section-head reveal"><span class="section-index" aria-hidden="true">'+n+'</span><h2>'+fmt(title)+'</h2>'+(''.join(para(x) for x in body) if body else '')+'</div>'
def closing(title,body='',secondary=True):
 return '<div class="section-close reveal"><h3>'+fmt(title)+'</h3>'+(para(body) if body else '')+action(secondary)+'</div>'
s=S[1]
photos=['cuidado.webp','tensao.webp','cansaco.webp','insonia.webp','ansiedade.webp','familia.webp','documentos.webp']
alts=['Pessoa idosa recebendo apoio em casa.','Mulher com a mão no ombro.','Mulher descansando na cama.','Pessoa acordada durante a noite.','Mulher pensativa junto à janela.','Família reunida na sala.','Pessoas conversando à mesa com documentos.']
rest='<section class="recognition section" id="rotina"><div class="wrap">'+sectionhead('01',s[1])+'<div class="routine-grid" id="rotina-cards" tabindex="0" aria-label="Cenas da rotina; deslize para ver mais">'
for i in range(7):
 rest+='<article class="routine-card reveal">'+img(photos[i],alts[i])+'<div><h3>'+fmt(s[2+i*2])+'</h3>'+para(s[3+i*2])+'</div></article>'
rest+='</div><div class="swipe-progress" aria-hidden="true"><span></span></div>'+closing(s[17],s[19],False)+'</div></section>'
s=S[2]
diagram='''<figure class="system-figure reveal" aria-label="Representação ilustrativa do sistema endocanabinoide e processos que ajuda a modular"><svg viewBox="0 0 540 640" role="img" aria-labelledby="system-title"><title id="system-title">Sistema endocanabinoide: dor, sono, humor, apetite e resposta inflamatória</title><defs><radialGradient id="aura"><stop stop-color="#d0e5d0"/><stop offset="1" stop-color="#edf5ef" stop-opacity="0"/></radialGradient></defs><ellipse cx="270" cy="318" rx="235" ry="286" fill="url(#aura)"/><g fill="none" stroke="#536d65" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" class="body-outline"><path d="M270 62c-27 0-39 20-36 48 2 20 13 39 36 39s34-19 36-39c3-28-9-48-36-48Z"/><path d="M250 144v24l-49 17c-17 7-23 26-27 46l-27 120c-5 25 13 31 20 11l41-114 5 115-16 170c-3 32 24 35 28 9l34-169h22l34 169c4 26 31 23 28-9l-16-170 5-115 41 114c7 20 25 14 20-11l-27-120c-4-20-10-39-27-46l-49-17v-24"/><path d="M270 175v176" stroke-dasharray="2 8"/></g><g class="body-connectors" stroke="#749680" fill="none" stroke-width="1"><path d="M270 96h80l32-18h57"/><path d="M257 114h-66l-31 37H73"/><path d="M270 241h97l28-15h54"/><path d="M271 321h-82l-31 26H61"/><path d="M307 442h69l14 41h83"/></g><g fill="#15934c" class="body-points"><circle cx="270" cy="96" r="7"/><circle cx="257" cy="114" r="6"/><circle cx="270" cy="241" r="7"/><circle cx="271" cy="321" r="7"/><circle cx="307" cy="442" r="7"/></g><g font-family="Nunito Sans,sans-serif" fill="#222e59" font-size="19"><text x="386" y="66">Sono</text><text x="64" y="140">Humor</text><text x="400" y="214">Dor</text><text x="53" y="335">Apetite</text><text x="369" y="511">Resposta</text><text x="369" y="534">inflamatória</text></g></svg><figcaption>Sistema endocanabinoide <span>Representação ilustrativa</span></figcaption></figure>'''
rest+='<section class="science section" id="ciencia"><div class="wrap">'+sectionhead('02',s[2],[s[4]])+'<div class="science-grid"><div class="science-copy">'+''.join(para(s[i],'reveal') for i in range(5,9))+'<div class="diagram-mobile"></div>'+para(s[10],'reveal')+'</div>'+diagram+'</div>'
rest+='<figure class="comparison reveal"><div class="compare-stage" style="--split:50%">'+img('leitura.webp','Cena ilustrativa de uma pessoa lendo tranquilamente em casa.','compare-base')+'<div class="compare-before">'+img('tensao.webp','Cena ilustrativa de tensão na rotina.')+'</div><div class="compare-label left">'+fmt(s[12].split(': ',1)[1])+'</div><div class="compare-label right">'+fmt(s[13].split(': ',1)[1])+'</div><div class="compare-handle" aria-hidden="true"><span>↔</span></div><input type="range" min="5" max="95" value="50" aria-label="Arraste para comparar as duas cenas ilustrativas"></div><figcaption>Cenas ilustrativas. Cada pessoa tem uma resposta individual ao tratamento.</figcaption></figure>'
rest+='<div class="medicinal-panel reveal"><div class="medicinal-image">'+img('frasco-editado.webp','Mãos segurando conta-gotas e frasco âmbar sem rótulo.')+'</div><div class="medicinal-copy"><h3>'+fmt(s[16])+'</h3>'+para(s[17])+para(s[18])+'<div class="concentrations" aria-hidden="true"><span>CBD</span><span>THC</span><span>Diferentes<br>concentrações</span></div>'+para(s[19].split(': ',1)[1],'info-box')+'</div></div>'
rest+='<div class="personal-care reveal"><div><h3>'+fmt(s[22])+'</h3>'+para(s[23])+'</div>'+img('consulta.webp','Casal em casa conversando pelo notebook.')+'</div><div class="science-close reveal">'+para(s[25])+action(False)+'</div></div></section>'
s=S[3]
conditions=[]
for i in range(6):
 j=5+i*3
 conditions.append({'title':s[j].replace(' (card de destaque)',''),'intro':s[j+1].split(': ',1)[1],'body':s[j+2].split(': ',1)[1],'image':['caminhada.webp','leitura.webp','familia.webp','familia.webp','caminhada.webp','cuidado.webp'][i]})
def condcard(i):
 c=conditions[i]
 return '<button class="condition-card" data-condition="'+str(i)+'" aria-haspopup="dialog">'+img(c['image'],'Cena de rotina ilustrativa.')+'<span class="condition-content"><span class="condition-title">'+fmt(c['title'])+'</span><span class="condition-intro">'+fmt(c['intro'])+'</span><span class="condition-plus" aria-hidden="true">+</span></span></button>'
rest+='<section class="conditions section" id="condicoes"><div class="wrap">'+sectionhead('03',s[1],[s[3],s[4]])+'<div class="featured-conditions reveal">'+condcard(0)+condcard(1)+'</div><div class="condition-carousel reveal"><div class="condition-track" id="condicoes-cards" tabindex="0" aria-label="Outras condições acompanhadas pela curadoria">'+''.join(condcard(i) for i in range(2,6))+'</div><div class="carousel-controls"><button data-carousel="-1" aria-label="Condição anterior">←</button><button class="autoplay-toggle" aria-label="Pausar movimento das condições">Pausar</button><button data-carousel="1" aria-label="Próxima condição">→</button></div></div><div class="section-close reveal">'+para(s[24])+'<h3 class="small-close">'+fmt(s[25])+'</h3>'+action()+'</div></div></section>'
s=S[4]
rest+='<section class="journey section" id="jornada"><div class="wrap">'+sectionhead('04',s[1],[s[3]])+'<div class="timeline"><div class="timeline-rail" aria-hidden="true"><span></span></div>'
steps=[(4,[5],'perfil'),(6,[7],'agendamento'),(8,[9,10],'consulta'),(11,[12],'acompanhamento')]
for i,(title,pars,kind) in enumerate(steps):
 if kind=='perfil': visual='<div class="real-screen"><div class="screen-top" aria-hidden="true"><i></i><i></i><i></i></div>'+img('perfil-real.png','Captura real de um perfil da listagem pública de profissionais da Canabinote.')+'<span class="screen-caption">'+logo()+'</span></div>'
 elif kind=='agendamento': visual='<div class="appointment-photo">'+img('consulta.webp','Casal organizando sua rotina em casa com um notebook.')+'</div>'
 elif kind=='consulta':visual=img('consulta.webp','Pessoas conversando por videochamada no notebook em casa.')
 else:visual='<div class="phone-visual">'+img('acompanhamento.webp','Tela de acompanhamento Canabinote pelo WhatsApp: Como você avalia seu bem-estar nos últimos 7 dias? Muito melhor, Melhor, Sem alteração, Pior, Muito pior.')+'</div>'
 rest+='<article class="journey-step reveal"><div class="step-visual '+kind+'">'+visual+'</div><span class="step-number" aria-hidden="true">0'+str(i+1)+'</span><div class="step-copy"><h3>'+fmt(s[title])+'</h3>'+''.join(para(s[j]) for j in pars)+'</div></article>'
rest+='</div><div class="journey-summary reveal"><span>Escolho meu médico</span><b aria-hidden="true">→</b><span>agendo</span><b aria-hidden="true">→</b><span>converso</span><b aria-hidden="true">→</b><span>continuo acompanhado.</span></div>'+closing(s[14])+'</div></section>'
s=S[5]
rest+='<section class="why section" id="canabinote"><div class="wrap">'+sectionhead('05',s[1],[s[3],s[4]])+'<div class="bento">'
rest+='<article class="bento-doctors reveal"><div class="bento-media doctors-media"><div class="real-screen">'+img('perfil-real.png','Perfil real de profissional na listagem pública da Canabinote.')+'</div></div><div class="bento-copy"><h3>'+fmt(s[5])+'</h3>'+para(s[6])+para(s[7],'emphasis')+'</div></article>'
rest+='<article class="bento-products reveal"><div class="bento-media">'+img('frasco-editado.webp','Frascos de vidro âmbar sem rótulos e conta-gotas.')+'</div><div class="bento-copy"><h3>'+fmt(s[8])+'</h3>'+para(s[9])+'</div></article>'
rest+='<article class="bento-prescription reveal"><div class="prescription-type">'+logo()+'<div>Produto <span>·</span> Formulação<br>Concentração <span>·</span> Dose<br>Orientações do médico</div></div><div class="bento-copy"><h3>'+fmt(s[10])+'</h3>'+para(s[11])+para(s[12])+para(s[13],'prescription-signature')+'</div></article>'
rest+='<article class="bento-monitoring reveal"><div class="bento-media monitoring-media">'+img('casal-editado.webp','Casal em um momento tranquilo em casa.')+img('acompanhamento.webp','Tela real de referência do acompanhamento no WhatsApp com perguntas de bem-estar.','monitoring-phone')+'</div><div class="bento-copy"><h3>'+fmt(s[14])+'</h3>'+para(s[15])+'</div></article></div><div class="brand-statement reveal"><p>Ciência para orientar.</p><p>Tecnologia para conectar.</p><p>Acompanhamento para continuar cuidando.</p></div><div class="center-actions">'+action()+'</div></div></section>'
s=S[6]
rest+='<section class="final-section" id="conversar"><div class="final-photo">'+img('casal-editado.webp','Casal aproveitando um momento de tranquilidade em casa.')+'</div><div class="wrap final-inner"><div class="final-copy reveal"><h2>'+fmt(s[1])+'</h2>'+para(s[2])+para(s[3])+para(s[4],'final-invite')+action(False)+para(s[6],'cta-note')+'<a class="secondary" href="'+MD+'" target="_blank" rel="noopener noreferrer">'+fmt(s[7])+'</a></div></div></section><footer><div class="wrap footer-inner">'+logo()+para(s[10])+'</div></footer>'
rest+='<dialog id="condition-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Fechar detalhes">×</button><div class="dialog-image"></div><div class="dialog-body"><h2 id="dialog-title"></h2><p id="dialog-description"></p>'+action(False)+'</div></dialog><a class="floating-wa" href="'+html.escape(WA)+'" target="_blank" rel="noopener noreferrer" hidden>Quero saber mais <span aria-hidden="true">↗</span></a><script type="application/json" id="condition-data">'+json.dumps(conditions,ensure_ascii=False).replace('</','<\/')+'</script>'
hero=hero.replace('casal.jpg','casal-editado.webp')
